### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bligny** [minimalcode-org/minimalcode-parent#1]
Hello

Your "Beans" library looks really **great** ! I like it very much :-D

I would like to submit you a suggestion as possible improvement, regarding the auto-instancing features in the context of indexed properties.

Would it be possible to accept(*) property pattern like;

`wrapper.setValue("children[0].firstName", "Bernard");`

Instead of:

```
wrapper.setValue("children[0]", new Child());
wrapper.setValue("children[0].firstName", "Bernard");
```

Kind regards,

Bernard.
Enterprise Java Architect

---

(*) Currently stack-trace is:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at org.minimalcode.beans.ObjectWrapper.getIndexedValue(ObjectWrapper.java:602)
    at org.minimalcode.beans.ObjectWrapper.getValue(ObjectWrapper.java:549)
    at org.minimalcode.beans.ObjectWrapper.setValue(ObjectWrapper.java:690)
    at org.minimalcode.beans.ObjectWrapper.setValue(ObjectWrapper.java:303)
    at net.haulogy.cms.gateway.test.IndexedTest.whishItCouldWork(IndexedTest.java:41)
```

**Comment by bligny** [comment]
Moved to https://github.com/minimalcode-org/minimalcode-beans/issues/4
